package com.bank.scoreVerification.identityverification.repositories

import com.bank.scoreVerification.identityverification.domain.IdentityVerificationRecord
import org.springframework.data.mongodb.repository.ReactiveMongoRepository
import org.springframework.stereotype.Repository
import java.util.UUID

@Repository
interface IdentityVerificationRepository : ReactiveMongoRepository<IdentityVerificationRecord, UUID>
